import{initializeApp}from"https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js";
import{getAuth,GoogleAuthProvider,onAuthStateChanged,signInWithPopup,signOut}from"https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js";
const BUILD="CGWEB123_FIX4_FIX1",VAULT="https://europe-west1-sport-505813.cloudfunctions.net/fitVault";
const app=initializeApp({apiKey:"AIzaSyDALtXWRoNHiD9oc4SqxH4tn7HY_08NI1A",authDomain:"sport-505813.firebaseapp.com",projectId:"sport-505813",storageBucket:"sport-505813.firebasestorage.app",messagingSenderId:"161388578171"});
const auth=getAuth(app),provider=new GoogleAuthProvider();provider.setCustomParameters({prompt:"select_account"});
let user=null,server=null,busy=false,timer=null;const $=id=>document.getElementById(id);
const read=(k,d=null)=>{try{const r=localStorage.getItem(k);return r?JSON.parse(r):d}catch{return d}},write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
function keys(){if(!user)return null;const p=`SPORT_CGWEB123_FIX3_FIX1_${user.uid}_`;return{state:p+"STATE",pause:p+"USER_PAUSE",server:p+"SERVER_FIX4"}}
function bundle(){const k=keys();return k?{keys:k,state:read(k.state),server:read(k.server)}:null}
function source(s){if(!s)return null;const c={...s};if(["SERVER_HANDOFF","SERVER_HANDOFF_PENDING"].includes(c.status)&&c.fix4_source_status)c.status=c.fix4_source_status;return c}
function msg(t,c=""){$("message").textContent=t||"";$("message").className=c}
async function api(action,{method="GET",body=null,query={}}={}){if(!user)throw new Error("Connexion Google requise.");const token=await user.getIdToken(),url=new URL(VAULT);url.searchParams.set("action",action);for(const[k,v]of Object.entries(query))if(v!==""&&v!=null)url.searchParams.set(k,String(v));const headers={Authorization:`Bearer ${token}`};let b=null;if(body!=null){headers["Content-Type"]="application/json";b=JSON.stringify(body)}const res=await fetch(url,{method,headers,body:b});const txt=await res.text();let p={};try{p=txt?JSON.parse(txt):{}}catch{p={error:txt}}if(!res.ok)throw new Error(p?.error||`HTTP ${res.status}`);return p}
function renderLocal(){const b=bundle(),s=b?.state;if(!user){$("localInfo").textContent="Connecte-toi pour lire le lot local.";$("transferButton").disabled=true;return}if(!s||!Array.isArray(s.queue)){$("localInfo").textContent="Aucun lot FIX3 trouvé dans ce navigateur.";$("transferButton").disabled=true;return}$("localInfo").textContent=`${Number(s.cursor||0)} / ${s.queue.length} · statut ${s.status||"?"} · ${Number(s.success_count||0)} réussite(s) · ${Number(s.failure_count||0)} échec(s) · ${Number(s.recovered_count||0)} récupérée(s)`;const same=server?.found&&String(server.source_batch_id||"")===String(s.batch_id||"");$("transferButton").disabled=busy||same||!s.batch_id||!s.queue.length}
function renderServer(r){server=r?.found?r:null;if(!server){$("serverStatus").textContent="Aucun lot";for(const id of["cursorMetric","successMetric","reviewMetric","failureMetric"])$(id).textContent="—";$("progress").max=1;$("progress").value=0;$("phaseInfo").textContent="—";$("pauseButton").disabled=$("resumeButton").disabled=$("reviewsButton").disabled=true;renderLocal();return}const st=String(server.status||"UNKNOWN"),cur=Number(server.cursor||0),tot=Number(server.total||0);$("serverStatus").textContent=`SERVER ${st}`;$("cursorMetric").textContent=`${cur} / ${tot}`;$("successMetric").textContent=Number(server.success_count||0);$("reviewMetric").textContent=Number(server.review_count||0);$("failureMetric").textContent=Number(server.failure_count||0);$("progress").max=Math.max(1,tot);$("progress").value=Math.min(cur,Math.max(1,tot));$("phaseInfo").textContent=`${server.current_phase||"IDLE"}${server.current_group_key?` · ${server.current_group_key}`:""}${server.last_error?` · ${server.last_error}`:""}`;$("pauseButton").disabled=busy||!["RUNNING","RETRYING"].includes(st);$("resumeButton").disabled=busy||!["PAUSED","PAUSING","RETRYING"].includes(st);$("reviewsButton").disabled=busy||Number(server.review_count||0)<=0;renderLocal()}
function fence(b,s){write(b.keys.pause,{requested:true,batch_id:String(s.batch_id||""),requested_at_ms:Date.now(),source:BUILD})}
function finalize(b,s,r){const cur=read(b.keys.state,s)||s;write(b.keys.state,{...cur,fix4_source_status:cur.fix4_source_status||s.status||"",status:"SERVER_HANDOFF",server_batch_id:String(r.batch_id||""),server_handoff_at_ms:Date.now()});write(b.keys.server,{batch_id:String(r.batch_id||""),source_batch_id:String(r.source_batch_id||s.batch_id||""),linked_at_ms:Date.now(),source:BUILD})}
async function discover(){const b=bundle(),id=String(b?.server?.batch_id||"");const r=await api("server_join_batch_status",{query:id?{batch_id:id}:{}});if(r?.found&&b?.state&&String(r.source_batch_id||"")===String(b.state.batch_id||""))finalize(b,source(b.state)||b.state,r);return r}
async function refresh(quiet=false){if(!user||busy){renderLocal();return}try{renderServer(await discover());if(!quiet)msg("État actualisé.","ok")}catch(e){msg(`Lecture serveur impossible : ${e.message}`,"err")}}
async function transfer(){if(!user||busy)return;const b=bundle(),s=source(b?.state);if(!b||!s?.batch_id||!Array.isArray(s.queue)||!s.queue.length){msg("Aucun lot local exploitable.","err");return}if(!confirm(`Transférer le lot côté serveur ?\n\n${Number(s.cursor||0)} / ${s.queue.length} déjà traité(s).\nLe serveur reprendra au curseur conservé.\n\nAprès confirmation, ne relance pas l'ancien batch depuis SPORT Web.`))return;busy=true;fence(b,s);$("transferButton").disabled=true;msg("Transfert vers Firestore et Cloud Tasks…","warn");try{const r=await api("server_join_batch_import",{method:"POST",body:{state:s}});finalize(b,s,r);renderServer(r);msg(`Transfert confirmé · ${Number(r.cursor||0)} / ${Number(r.total||0)} · traitement serveur.`,"ok")}catch(e){msg(`Réponse de transfert incertaine : ${e.message}. Clique Actualiser avant toute nouvelle tentative.`,"err")}finally{busy=false;await refresh(true)}}
async function pause(){if(!server?.batch_id||busy)return;busy=true;try{renderServer(await api("server_join_batch_pause",{method:"POST",body:{batch_id:server.batch_id}}));msg("Pause serveur demandée.","warn")}catch(e){msg(e.message,"err")}finally{busy=false}}
async function resume(){if(!server?.batch_id||busy)return;busy=true;try{renderServer(await api("server_join_batch_resume",{method:"POST",body:{batch_id:server.batch_id}}));msg("Reprise serveur demandée.","ok")}catch(e){msg(e.message,"err")}finally{busy=false}}
async function reviews(){if(!server?.batch_id||busy)return;busy=true;try{const r=await api("server_join_batch_reviews",{query:{batch_id:server.batch_id}}),rows=Array.isArray(r?.rows)?r.rows:[];$("reviews").textContent=rows.length?rows.map(x=>`#${Number(x.index)+1} · ${x.group_key||"?"}\n${x.reason||"À revoir"}`).join("\n\n"):"Aucun élément à revoir."}catch(e){$("reviews").textContent=e.message}finally{busy=false}}
$("loginButton").onclick=async()=>{try{await signInWithPopup(auth,provider)}catch(e){msg(`Connexion impossible : ${e.message}`,"err")}};$("logoutButton").onclick=()=>signOut(auth);$("transferButton").onclick=transfer;$("refreshButton").onclick=()=>refresh(false);$("pauseButton").onclick=pause;$("resumeButton").onclick=resume;$("reviewsButton").onclick=reviews;
onAuthStateChanged(auth,u=>{user=u||null;$("authBadge").textContent=user?`Connecté · ${user.email||"Google"}`:"Non connecté";$("loginButton").hidden=!!user;$("logoutButton").hidden=!user;renderLocal();if(timer)clearInterval(timer);if(user){void refresh(true);timer=setInterval(()=>{if(!document.hidden)void refresh(true)},5000)}else renderServer(null)});document.addEventListener("visibilitychange",()=>{if(!document.hidden&&user)void refresh(true)});
window.CGWEB123_FIX4_FIX1_STATUS=()=>({build:BUILD,lightweight_handoff:"LIGHTWEIGHT_HANDOFF001",app_boot_bypass:"APP_BOOT_BYPASS001",crash_safe_transfer:"CRASH_SAFE_TRANSFER001",server_progress_standalone:"SERVER_PROGRESS_STANDALONE001"});
console.info("CGWEB123 FIX4 FIX1 actif · LIGHTWEIGHT_HANDOFF001 / APP_BOOT_BYPASS001 / CRASH_SAFE_TRANSFER001 / SERVER_PROGRESS_STANDALONE001");
